name: flutter_data_components
description: RAD data components for Flutter business applications, including datasets, typed fields, grid and editors.
version: 1.0.4
homepage: https://fdcomponents.com
documentation: https://fdcomponents.com/docs/intro/
repository: https://github.com/fdcomponents/flutter_data_components
issue_tracker: https://github.com/fdcomponents/flutter_data_components/issues
topics:
  - crud
  - rad
  - components
  - dataset
  - data-grid

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0

dev_dependencies:
  analyzer: ^9.0.0
  flutter_lints: ^6.0.0

  flutter_test:
    sdk: flutter
  pubspec_parse: ^1.5.0

flutter:
