import 'package:flutter_data_components/fdc.dart';

const List<FdcOption<String>> customerStatusOptions = <FdcOption<String>>[
  FdcOption<String>(value: 'Lead', label: 'Lead'),
  FdcOption<String>(value: 'Active', label: 'Active'),
  FdcOption<String>(value: 'On Hold', label: 'On Hold'),
  FdcOption<String>(value: 'Inactive', label: 'Inactive'),
];

const List<FdcOption<String>> customerCountryOptions = <FdcOption<String>>[
  FdcOption<String>(value: 'Australia', label: 'Australia'),
  FdcOption<String>(value: 'Austria', label: 'Austria'),
  FdcOption<String>(value: 'Belgium', label: 'Belgium'),
  FdcOption<String>(value: 'Canada', label: 'Canada'),
  FdcOption<String>(value: 'Denmark', label: 'Denmark'),
  FdcOption<String>(value: 'Estonia', label: 'Estonia'),
  FdcOption<String>(value: 'Finland', label: 'Finland'),
  FdcOption<String>(value: 'France', label: 'France'),
  FdcOption<String>(value: 'Germany', label: 'Germany'),
  FdcOption<String>(value: 'Hong Kong', label: 'Hong Kong'),
  FdcOption<String>(value: 'Ireland', label: 'Ireland'),
  FdcOption<String>(value: 'Italy', label: 'Italy'),
  FdcOption<String>(value: 'Japan', label: 'Japan'),
  FdcOption<String>(value: 'Luxembourg', label: 'Luxembourg'),
  FdcOption<String>(value: 'Netherlands', label: 'Netherlands'),
  FdcOption<String>(value: 'New Zealand', label: 'New Zealand'),
  FdcOption<String>(value: 'Norway', label: 'Norway'),
  FdcOption<String>(value: 'Portugal', label: 'Portugal'),
  FdcOption<String>(value: 'Singapore', label: 'Singapore'),
  FdcOption<String>(value: 'Spain', label: 'Spain'),
  FdcOption<String>(value: 'Sweden', label: 'Sweden'),
  FdcOption<String>(value: 'Switzerland', label: 'Switzerland'),
  FdcOption<String>(
    value: 'United Arab Emirates',
    label: 'United Arab Emirates',
  ),
  FdcOption<String>(value: 'United Kingdom', label: 'United Kingdom'),
  FdcOption<String>(value: 'United States', label: 'United States'),
];

FdcDataSet createCustomerDataSet() {
  var nextCustomerId = 37;

  return FdcDataSet(
    fields: const <FdcFieldDef>[
      FdcIntegerField(
        name: 'customer_id',
        label: 'ID',
        isKey: true,
        storage: FdcFieldStorage(updateable: false),
      ),
      FdcStringField(
        name: 'company_name',
        label: 'Company',
        size: 120,
        required: true,
      ),
      FdcStringField(
        name: 'contact_name',
        label: 'Contact',
        size: 80,
        required: true,
      ),
      FdcStringField(name: 'email', label: 'Email', size: 120),
      FdcStringField(name: 'phone', label: 'Phone', size: 40),
      FdcStringField(name: 'city', label: 'City', size: 60),
      FdcStringField(name: 'country', label: 'Country', size: 60),
      FdcStringField(name: 'industry', label: 'Industry', size: 60),
      FdcStringField(name: 'status', label: 'Status', size: 30),
      FdcDecimalField(
        name: 'credit_limit',
        label: 'Credit Limit',
        precision: 12,
        scale: 2,
        minValue: 0,
      ),
      FdcBooleanField(name: 'active', label: 'Active', defaultValue: true),
      FdcDateField(name: 'registered_at', label: 'Registered'),
    ],
    adapter: FdcMemoryDataAdapter(rows: customerRows),
    onNewRecord: (dataSet) {
      dataSet.setFieldValue('customer_id', nextCustomerId++);
      dataSet.setFieldValue('company_name', 'New customer');
      dataSet.setFieldValue('status', 'Lead');
      dataSet.setFieldValue('credit_limit', 5000);
      dataSet.setFieldValue('active', true);
      dataSet.setFieldValue('registered_at', DateTime.now());
    },
  );
}

final List<Map<String, Object?>> customerRows = <Map<String, Object?>>[
  _customer(
    1,
    'Northstar Analytics',
    'Olivia Carter',
    'olivia.carter@northstar.example',
    '+44 20 7946 0184',
    'London',
    'United Kingdom',
    'Technology',
    'Active',
    25000,
    true,
    2023,
    2,
    14,
  ),
  _customer(
    2,
    'BluePeak Logistics',
    'Liam Bennett',
    'liam.bennett@bluepeak.example',
    '+49 30 9018 2201',
    'Berlin',
    'Germany',
    'Logistics',
    'Active',
    42000,
    true,
    2022,
    9,
    6,
  ),
  _customer(
    3,
    'Vertex Systems',
    'Emma Collins',
    'emma.collins@vertex.example',
    '+1 416 555 0142',
    'Toronto',
    'Canada',
    'Technology',
    'Lead',
    18000,
    true,
    2024,
    1,
    22,
  ),
  _customer(
    4,
    'Greenfield Foods',
    'Noah Mitchell',
    'noah.mitchell@greenfield.example',
    '+61 2 5550 1290',
    'Sydney',
    'Australia',
    'Food & Beverage',
    'Active',
    36000,
    true,
    2021,
    11,
    18,
  ),
  _customer(
    5,
    'Atlas Manufacturing',
    'Sophia Turner',
    'sophia.turner@atlas.example',
    '+31 20 555 0188',
    'Amsterdam',
    'Netherlands',
    'Manufacturing',
    'On Hold',
    55000,
    true,
    2020,
    5,
    11,
  ),
  _customer(
    6,
    'Brightline Media',
    'Ethan Parker',
    'ethan.parker@brightline.example',
    '+353 1 555 6021',
    'Dublin',
    'Ireland',
    'Media',
    'Active',
    15000,
    true,
    2023,
    7,
    3,
  ),
  _customer(
    7,
    'SilverOak Consulting',
    'Mia Anderson',
    'mia.anderson@silveroak.example',
    '+1 212 555 0198',
    'New York',
    'United States',
    'Consulting',
    'Active',
    22000,
    true,
    2022,
    4,
    26,
  ),
  _customer(
    8,
    'Harbor Technologies',
    'Lucas Morgan',
    'lucas.morgan@harbor.example',
    '+46 8 555 0130',
    'Stockholm',
    'Sweden',
    'Technology',
    'Lead',
    12000,
    true,
    2024,
    3,
    7,
  ),
  _customer(
    9,
    'Cedar Health Group',
    'Charlotte Reed',
    'charlotte.reed@cedar.example',
    '+65 6123 7701',
    'Singapore',
    'Singapore',
    'Healthcare',
    'Active',
    48000,
    true,
    2021,
    8,
    30,
  ),
  _customer(
    10,
    'Summit Retail',
    'James Foster',
    'james.foster@summit.example',
    '+64 9 555 8821',
    'Auckland',
    'New Zealand',
    'Retail',
    'Inactive',
    9000,
    false,
    2020,
    12,
    9,
  ),
  _customer(
    11,
    'Redwood Energy',
    'Amelia Brooks',
    'amelia.brooks@redwood.example',
    '+1 713 555 0102',
    'Houston',
    'United States',
    'Energy',
    'Active',
    67000,
    true,
    2019,
    6,
    17,
  ),
  _customer(
    12,
    'Aurora Finance',
    'Benjamin Hayes',
    'benjamin.hayes@aurora.example',
    '+41 44 555 1098',
    'Zurich',
    'Switzerland',
    'Finance',
    'Active',
    72000,
    true,
    2021,
    10,
    4,
  ),
  _customer(
    13,
    'Clearwater Labs',
    'Isabella Ward',
    'isabella.ward@clearwater.example',
    '+45 33 55 19 24',
    'Copenhagen',
    'Denmark',
    'Healthcare',
    'Lead',
    14000,
    true,
    2024,
    5,
    15,
  ),
  _customer(
    14,
    'Ironbridge Works',
    'Henry Cooper',
    'henry.cooper@ironbridge.example',
    '+44 121 555 0162',
    'Birmingham',
    'United Kingdom',
    'Manufacturing',
    'Active',
    51000,
    true,
    2020,
    2,
    27,
  ),
  _customer(
    15,
    'MapleWave Software',
    'Evelyn Scott',
    'evelyn.scott@maplewave.example',
    '+1 604 555 0119',
    'Vancouver',
    'Canada',
    'Technology',
    'Active',
    33000,
    true,
    2022,
    6,
    13,
  ),
  _customer(
    16,
    'Stonegate Partners',
    'Alexander Price',
    'alexander.price@stonegate.example',
    '+33 1 55 50 22 18',
    'Paris',
    'France',
    'Consulting',
    'On Hold',
    29000,
    true,
    2021,
    3,
    8,
  ),
  _customer(
    17,
    'Oakridge Distribution',
    'Harper Kelly',
    'harper.kelly@oakridge.example',
    '+32 2 555 0180',
    'Brussels',
    'Belgium',
    'Logistics',
    'Active',
    46000,
    true,
    2020,
    9,
    21,
  ),
  _customer(
    18,
    'Skyline Telecom',
    'Daniel Murphy',
    'daniel.murphy@skyline.example',
    '+34 91 555 0932',
    'Madrid',
    'Spain',
    'Technology',
    'Active',
    61000,
    true,
    2019,
    11,
    12,
  ),
  _customer(
    19,
    'Evergreen Markets',
    'Ella Richardson',
    'ella.richardson@evergreen.example',
    '+39 02 555 7742',
    'Milan',
    'Italy',
    'Retail',
    'Lead',
    17000,
    true,
    2024,
    2,
    19,
  ),
  _customer(
    20,
    'Riverside Foods',
    'Matthew Bailey',
    'matthew.bailey@riverside.example',
    '+43 1 555 2204',
    'Vienna',
    'Austria',
    'Food & Beverage',
    'Active',
    39000,
    true,
    2022,
    8,
    1,
  ),
  _customer(
    21,
    'Beacon Medical',
    'Avery Hughes',
    'avery.hughes@beacon.example',
    '+47 22 55 71 40',
    'Oslo',
    'Norway',
    'Healthcare',
    'Active',
    53000,
    true,
    2021,
    1,
    25,
  ),
  _customer(
    22,
    'Copperline Industries',
    'Sebastian Gray',
    'sebastian.gray@copperline.example',
    '+358 9 555 1044',
    'Helsinki',
    'Finland',
    'Manufacturing',
    'Inactive',
    31000,
    false,
    2018,
    7,
    16,
  ),
  _customer(
    23,
    'Pioneer Capital',
    'Scarlett Watson',
    'scarlett.watson@pioneer.example',
    '+352 26 55 11 80',
    'Luxembourg',
    'Luxembourg',
    'Finance',
    'Active',
    88000,
    true,
    2020,
    10,
    29,
  ),
  _customer(
    24,
    'Lighthouse Digital',
    'Jack Peterson',
    'jack.peterson@lighthouse.example',
    '+372 6 555 209',
    'Tallinn',
    'Estonia',
    'Media',
    'Lead',
    11000,
    true,
    2024,
    4,
    8,
  ),
  _customer(
    25,
    'Crescent Mobility',
    'Grace Phillips',
    'grace.phillips@crescent.example',
    '+971 4 555 0191',
    'Dubai',
    'United Arab Emirates',
    'Logistics',
    'Active',
    58000,
    true,
    2022,
    12,
    14,
  ),
  _customer(
    26,
    'Orchard Commerce',
    'Samuel Evans',
    'samuel.evans@orchard.example',
    '+81 3 5550 1840',
    'Tokyo',
    'Japan',
    'Retail',
    'Active',
    44000,
    true,
    2021,
    5,
    19,
  ),
  _customer(
    27,
    'Meridian Advisory',
    'Chloe Stewart',
    'chloe.stewart@meridian.example',
    '+852 5550 2201',
    'Hong Kong',
    'Hong Kong',
    'Consulting',
    'On Hold',
    26000,
    true,
    2020,
    4,
    6,
  ),
  _customer(
    28,
    'NovaGrid Power',
    'Leo Morris',
    'leo.morris@novagrid.example',
    '+49 40 555 0146',
    'Hamburg',
    'Germany',
    'Energy',
    'Active',
    76000,
    true,
    2019,
    9,
    23,
  ),
  _customer(
    29,
    'Willow Health',
    'Lily Rogers',
    'lily.rogers@willow.example',
    '+1 617 555 0177',
    'Boston',
    'United States',
    'Healthcare',
    'Active',
    47000,
    true,
    2023,
    1,
    10,
  ),
  _customer(
    30,
    'Keystone Engineering',
    'David Cook',
    'david.cook@keystone.example',
    '+1 312 555 0181',
    'Chicago',
    'United States',
    'Manufacturing',
    'Lead',
    34000,
    true,
    2024,
    6,
    5,
  ),
  _customer(
    31,
    'Suncrest Hospitality',
    'Hannah Bell',
    'hannah.bell@suncrest.example',
    '+351 21 555 1082',
    'Lisbon',
    'Portugal',
    'Hospitality',
    'Active',
    28000,
    true,
    2022,
    3,
    28,
  ),
  _customer(
    32,
    'Granite Insurance',
    'Joseph Ross',
    'joseph.ross@granite.example',
    '+353 1 555 6044',
    'Dublin',
    'Ireland',
    'Finance',
    'Active',
    63000,
    true,
    2020,
    8,
    20,
  ),
  _customer(
    33,
    'Cloudberry Studio',
    'Zoey Wood',
    'zoey.wood@cloudberry.example',
    '+46 31 555 4402',
    'Gothenburg',
    'Sweden',
    'Media',
    'Lead',
    13000,
    true,
    2024,
    3,
    25,
  ),
  _customer(
    34,
    'GoldenGate Imports',
    'Owen Barnes',
    'owen.barnes@goldengate.example',
    '+1 415 555 0160',
    'San Francisco',
    'United States',
    'Logistics',
    'Active',
    49000,
    true,
    2021,
    7,
    12,
  ),
  _customer(
    35,
    'Elm Street Ventures',
    'Nora Powell',
    'nora.powell@elmstreet.example',
    '+1 206 555 0194',
    'Seattle',
    'United States',
    'Finance',
    'On Hold',
    81000,
    true,
    2019,
    5,
    7,
  ),
  _customer(
    36,
    'Polar Retail Group',
    'Nathan Long',
    'nathan.long@polar.example',
    '+47 55 555 302',
    'Bergen',
    'Norway',
    'Retail',
    'Inactive',
    16000,
    false,
    2020,
    1,
    31,
  ),
];

Map<String, Object?> _customer(
  int id,
  String company,
  String contact,
  String email,
  String phone,
  String city,
  String country,
  String industry,
  String status,
  num creditLimit,
  bool active,
  int year,
  int month,
  int day,
) {
  return <String, Object?>{
    'customer_id': id,
    'company_name': company,
    'contact_name': contact,
    'email': email,
    'phone': phone,
    'city': city,
    'country': country,
    'industry': industry,
    'status': status,
    'credit_limit': creditLimit,
    'active': active,
    'registered_at': DateTime(year, month, day),
  };
}
